name: he_storage
description: HE implementation of the local storage that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
#  flutter: 3.3.7

dependencies:
  equatable: ^2.0.3
  #stream test
#  either_dart: ^0.3.0
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  he_api:
    path: ../he_api
  json_annotation: ^4.7.0
  meta: ^1.7.0
  rx_shared_preferences: ^3.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.0-nullsafety
  async_zip: ^0.0.2
  injectable: ^2.1.0


dev_dependencies:
  #stream test
#  build_runner: ^2.2.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  #stream test
  very_good_analysis: ^3.1.0
  injectable_generator: ^2.1.3

#  shared_preferences_platform_interface: ^2.1.0
#  built_value_generator: ^8.4.2

