name: auth_repository
description: user authentication package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.3
  firebase_auth: 4.1.0
  firebase_core: 2.1.1
#  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  meta: 1.8.0
  user_api:
    path: ../user_api


dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  mocktail: 0.3.0
  very_good_analysis: 3.1.0
  analyzer: ^4.7.0

#dependency_overrides:
#  firebase_core_platform_interface: 4.4.1