name: auth_repository
description: user authentication package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  user_api:
    path: ../user_api


dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0