name: he
description: Healthy Entrepreneurs

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  auth_repository:
    path: packages/auth_repository
  cache:
    path: packages/cache
  bloc: ^8.0.2
  equatable: ^2.0.3
  flow_builder: ^0.0.4
  firebase_core: ^1.11.0
  flutter_bloc: ^8.0.1
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^2.1.0
  meta: ^1.3.0
  cloud_firestore: ^2.5.3
#  cloud_firestore: ^3.1.7
  firebase_storage: ^10.0.0

#  hydrated_bloc: ^8.0.0
  path_provider: ^2.0.8
  easy_localization: ^3.0.0
  intl_utils: ^2.6.1
  transparent_image: ^2.0.0

  #Start File System Plugins
  external_path: ^1.0.1
  permission_handler: ^8.3.0
  #End

  #Start HTML
  http: ^0.13.4
  universal_html: ^2.0.8
#  universal_io: ^2.0.4
  url_launcher: ^6.0.9
  path: ^1.8.0
  #remove plus
  webview_flutter: ^3.0.0
  flutter_inappwebview: ^5.3.2
  flutter_widget_from_html: ^0.8.5
  just_audio_web: ^0.4.3
  chewie: any
  video_player: ^2.2.3
#  flutter_html: ^2.1.0
#  ota_update: ^4.0.1
  #End HTML
  #OTA START
#  ota_enabled


dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.3.0
  flutter_launcher_icons: ^0.9.2

flutter:
  generate: true
  # The following line ensures that the Material Icons font is jquery.min.js
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/translations/
    - assets/icon/icon.png
    - assets/images/lake.png
    - assets/images/logo.png
    - assets/images/grid.png
    - assets/quiz/index.html
    - assets/quiz/jquery.min.js
    - assets/quiz/index.js
    - assets/quiz/w3.css
    - assets/quiz/quiz.css
    - assets/www/index.html
    - assets/www/styles/style.css

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/icon.png"