name: he
description: Healthy Entrepreneurs

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1 # 1.0.0+1 , 1.2.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
#  flutter: 3.3.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  he_api:
    path: packages/he_api
  he_storage:
    path: packages/he_storage
  auth_repo:
    path: packages/auth_repo
  theme_locale_repo:
    path: packages/theme_locale_repo
  bloc: ^8.1.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  flow_builder: ^0.0.9
  bloc_concurrency: ^0.2.0
  firebase_auth: 4.1.0
  firebase_core: ^2.4.1
  flutter_bloc: ^8.1.1
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^3.0.1
  meta: ^1.3.0
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.16
  firebase_core_platform_interface: ^4.5.1
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.8
  transparent_image: ^2.0.0
  #Start File System Plugins
  external_path: ^1.0.1
  permission_handler: ^10.2.0
  #End
  #namu
  injectable: ^2.1.0
  #namu end
  #Start HTML
  http: ^0.13.4
  universal_html: ^2.0.8
  #  universal_io: ^2.0.4
  path: ^1.8.0
  #remove plus
  flutter_inappwebview: ^5.7.2+3
  flutter_widget_from_html: ^0.9.1
  just_audio_web: ^0.4.3
  video_player: ^2.2.3
  #  open_file: ^3.2.1
  install_plugin_v2: ^1.0.0
  package_info_plus: ^3.0.2
  disposebag: ^1.5.1
#  tuple: ^2.0.1
#  go_router: ^6.0.1
  rx_shared_preferences: ^3.0.0
  chewie: ^1.3.6
  rxdart: ^0.27.7
  copy_with_extension_gen: ^5.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  json_annotation: ^4.7.0
#  get_storage: ^2.0.3
#  image_picker: ^0.8.6
#  archive: ^3.3.6
  connectivity_plus: ^3.0.2
  network_info_plus: ^3.0.2
  device_info_plus: ^8.2.0
#  collection: ^1.17.0
  flutter_spinkit: ^5.1.0
  async_zip:
    git:
      url: https://github.com/njovujsh/async-zip.git
      ref: master
#  webview_flutter_plus: ^0.3.0+2
  flutter_cache_manager_firebase:
    git:
      url: https://github.com/njovujsh/flutter_cache_manager_firebase.git
      ref: main
  url_launcher: ^6.1.10
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
#  flutter_background_service: ^2.4.6
#  animations: ^2.0.7
  workmanager: ^0.5.1
  flutter_local_notifications: ^13.0.0
#  flutter_background_executor: ^1.0.0

  broadcast_bloc: ^0.1.0-dev.2 #https://pub.dev/packages/broadcast_bloc
  intl: ^0.17.0
#  android_alarm_manager_plus: ^2.1.2

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.1
  flutter_lints: ^2.0.1
  very_good_analysis: ^3.1.0
  plugin_platform_interface: ^2.1.3
  flutter_launcher_icons: ^0.11.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  objectbox_generator: ^2.0.0
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  freezed: ^2.2.0
  json_serializable: ^6.3.1
  faker: ^2.1.0
#  https://pub.dev/packages/isolate_downloader

#dependency_overrides:
#  ffi: ^1.1.2
#  build: ^2.0.0

flutter:
  generate: true
  # The following line ensures that the Material Icons font is jquery.min.js
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/quiz/
    - assets/survey/

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/icon.png"
