name: nl_health_app
description: Healthy Entrepreneurs.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.3 < 3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  http: ^0.13.3
#  sqfentity: ^2.0.0
#  sqfentity_gen: ^2.0.0
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  path_provider: ^2.0.2
  permission_handler: ^8.1.2
  file_utils: ^1.0.1
  dio: ^4.0.0
#  ext_storage: ^1.0.3
  chewie: ^1.2.2
  provider: ^5.0.0
  video_player: ^2.2.3
  url_launcher: ^6.0.9
  cool_stepper: ^1.2.1
  flutter_archive: ^4.0.1
  toggle_switch: ^1.2.0
  filesystem_picker: ^2.0.0-nullsafety.0
  connectivity: ^3.0.6
  intl: ^0.17.0
  objectbox: ^1.1.1
  objectbox_flutter_libs: ^1.1.1
  android_alarm_manager_plus: ^1.0.2
  archive: ^3.1.2
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.0.7
  flutter_phoenix: ^1.0.0
  external_path: ^1.0.1
  get_it: ^7.2.0
  universal_html: ^2.0.8
  webview_flutter_plus: ^0.2.2
  flutter_inappwebview: ^5.3.2
  flutter_widget_from_html: ^0.7.0
  just_audio_web: ^0.4.2
#  flutter_widget_from_html
  flutter_html: ^2.1.0
  tuple: ^2.0.0
#  firebase_remote_config: ^0.10.0+3
#  flutter_webrtc: ^0.6.7
#  firebase_image
  cloud_firestore: ^2.4.0
  firebase_storage: ^8.0.0
  firebase_image: ^1.0.1
  #Relatable flutter_cache_manager
#  firebase_auth: ^3.1.1
#  firestore_ui: ^1.20.0
  image_picker: ^0.8.3+2
  flutter_cache_manager_firebase: ^2.0.1
#  oktoast: ^3.1.1

dev_dependencies:
  test: '>=1.15.0 <2.0.0'
  build_runner: ^2.0.6
  build_verify: ^2.0.0
  objectbox_generator: ^1.1.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
  flutter_launcher_icons: ^0.9.0
#  async_builder: ^1.3.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icon/
     - assets/video/
     - assets/video/malaria.mp4
     - assets/images/schermafbeelding.png
     - assets/images/grid.png
     - assets/survey_form.json
     - assets/survey/index.html
     - assets/survey/modern.css
     - assets/survey/survey.jquery.min.js
     - assets/survey/index.js
     - assets/survey/index.css
     - assets/survey/jquery.min.js
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Raleway-Black.ttf
        - asset: fonts/Raleway-BlackItalic.ttf
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-BoldItalic.ttf
        - asset: fonts/Raleway-ExtraBold.ttf
        - asset: fonts/Raleway-ExtraBoldItalic.ttf
        - asset: fonts/Raleway-ExtraLight.ttf
        - asset: fonts/Raleway-ExtraLightItalic.ttf
        - asset: fonts/Raleway-Italic.ttf
        - asset: fonts/Raleway-Light.ttf
        - asset: fonts/Raleway-LightItalic.ttf
        - asset: fonts/Raleway-Medium.ttf
        - asset: fonts/Raleway-MediumItalic.ttf
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-SemiBold.ttf
        - asset: fonts/Raleway-SemiBoldItalic.ttf
        - asset: fonts/Raleway-Thin.ttf
        - asset: fonts/Raleway-ThinItalic.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
