name: he
description: Healthy Entrepreneurs

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1   # 1.0.0+1 , 1.2.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
#  flutter: 3.3.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  he_api:
    path: packages/he_api
  auth_repo:
    path: packages/auth_repo
  theme_locale_repo:
    path: packages/theme_locale_repo
  bloc: ^8.1.0
  equatable: ^2.0.3
  flow_builder: ^0.0.9
  bloc_concurrency: ^0.2.0
  firebase_core: ^2.1.1
  flutter_bloc: ^8.1.1
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^3.0.1
  meta: ^1.3.0
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.8
  transparent_image: ^2.0.0

  #Start File System Plugins
  external_path: ^1.0.1
  permission_handler: ^10.2.0
  #End

  #Start HTML
  http: ^0.13.4
  universal_html: ^2.0.8
#  universal_io: ^2.0.4
  url_launcher: ^6.0.9
  path: ^1.8.0
  #remove plus
  webview_flutter: ^3.0.0
  flutter_inappwebview: ^5.3.2
  flutter_widget_from_html: ^0.8.5
  just_audio_web: ^0.4.3
  video_player: ^2.2.3
#  open_file: ^3.2.1
  install_plugin_v2: ^1.0.0
  package_info_plus: ^3.0.1
  disposebag: ^1.5.1
  tuple: ^2.0.1
  go_router: ^5.2.4
  rx_shared_preferences: ^3.0.0
  chewie: ^1.3.6
  rxdart: ^0.27.7
#  connectivity_plus


dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  fake_async: ^1.3.1
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.3.0

flutter:
  generate: true
  # The following line ensures that the Material Icons font is jquery.min.js
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/icon/icon.png
    - assets/images/lake.png
    - assets/images/logo.png
    - assets/images/grid.png
    - assets/quiz/index.html
    - assets/quiz/jquery.min.js
    - assets/quiz/index.js
    - assets/quiz/w3.css
    - assets/quiz/quiz.css
    - assets/survey/index.html
    - assets/survey/modern.css
    - assets/survey/survey.jquery.min.js
    - assets/survey/index.js
    - assets/survey/index.css
    - assets/survey/jquery.min.js

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/icon.png"