name: nl_health_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.5.0
  http: ^0.12.2
  sqfentity: ^1.4.0+3
  sqfentity_gen:
  shared_preferences: ^0.5.12+2
  fluttertoast: ^3.0.4
  path_provider: ^1.6.21
  permission_handler: ^5.0.1+1
  file_utils: ^0.1.4
  dio: ^3.0.10
  ext_storage: ^1.0.3
  flutter_html: ^1.1.1
  themify_flutter: ^1.0.0
  video_player:
  universal_html: ^1.2.3
  webview_flutter_plus: ^0.1.1+10
  url_launcher: ^5.7.10
  flutter_webview_plugin: ^0.3.11
  flutter_inappwebview: ^4.0.0+4
  chewie: ^0.12.0
  cool_stepper: ^1.1.3
  flutter_archive: ^1.0.3
  toggle_switch: ^0.1.8
  filesystem_picker: ^1.0.3
  workmanager:
  connectivity: ^2.0.2
  intl:
  objectbox: ^0.11.0
  objectbox_flutter_libs: any
  flutter_phoenix: ^0.1.0
  stacked: ^1.6.0
  provider_architecture: 1.0.6
  android_alarm_manager:
  archive: any


  #webview_flutter: ^1.0.7
  survey_module:
    # When depending on this package from a real application you should use:
    #   survey_module: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ./survey_module


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  build_verify:
  objectbox_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
  flutter_launcher_icons: ^0.8.1

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icon/
     - assets/video/
     - assets/video/malaria.mp4
     - assets/images/schermafbeelding.png
     - assets/survey_form.json
     - assets/survey/index.html
     - assets/survey/modern.css
     - assets/survey/survey.jquery.min.js
     - assets/survey/index.js
     - assets/survey/index.css
     - assets/survey/jquery.min.js
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
