name: theme_locale_repo
description: Theme and Language Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  disposebag: ^1.5.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  google_fonts: ^3.0.1
  google_fonts: ^4.0.4
  intl_utils: ^2.7.0
  rx_shared_preferences: ^3.0.0
  rxdart: ^0.27.7
  tuple: ^2.0.1



dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0


flutter:
#  generate: true
  # The following line ensures that the Material Icons font is jquery.min.js
  uses-material-design: true
