name: he_api
description: HE package handling of the firebase objects of HE .
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  # cloud_firestore_odm: ^1.0.0-dev.45
  copy_with_extension_gen: ^5.0.0
  dio: ^4.0.6
  dio_smart_retry: ^1.3.2
  equatable: ^2.0.3
  json_annotation: ^4.7.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.3.3
  # cloud_firestore_odm_generator: ^1.0.0-dev.45
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
