name: user_api
description: Queries from remote to authenticate user
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.1
  coverage: ^1.0.3
  json_serializable: ^4.1.4
  mocktail: ^0.2.0
  test: ^1.16.4
  very_good_analysis: ^2.4.0