name: user_api
description: Queries from remote to authenticate user
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.0
#  json_annotation: 4.7.0
  json_annotation: ^4.4.0

dev_dependencies:
#  build_runner: 2.2.0
  build_runner: ^2.3.2
  coverage: 1.6.1
  json_serializable: ^6.1.4
  mocktail: 0.3.0
  test: 1.21.7
  very_good_analysis: 3.1.0