name: form_inputs
description: form facets for the entire application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  formz: ^0.4.0

dev_dependencies:
  very_good_analysis: ^2.4.0