name: auth_repo
description: Dart package which manages the HE user and firebase auth domain
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  equatable: ^2.0.3
  firebase_auth: 4.1.0
  firebase_core: ^2.4.1
  firebase_core_platform_interface: ^4.5.1
  # Unfortunately, a breaking change was introduced in 4.5.2.
  # https://github.com/firebase/flutterfire/issues/9806
  flutter:
    sdk: flutter
  he_api:
    path: ../he_api
  he_storage:
    path: ../he_storage
  meta: ^1.7.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3
  very_good_analysis: ^3.1.0

