import 'package:objectbox/objectbox.dart';

@Entity()
class BookDataModel {
  @Id()
  int id; // Autogenerated id
  String bookId;
  String chapterId;
  String courseId;
  String userId;
  bool isPending;

  @Property(type: PropertyType.date)
  DateTime dateCreated;

  BookDataModel({
    this.id = 0, // Default value for autogenerated id
    required this.bookId,
    required this.chapterId,
    required this.userId,
    required this.courseId,
    required this.isPending,
  }) : dateCreated = DateTime.now();

  @override
  String toString() {
    return 'BookDataModel{id: $id, bookId: $bookId, chapterId: $chapterId,courseId: $courseId, isPending: $isPending, dateCreated: $dateCreated}';
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'bookId': bookId,
      'chapterId': chapterId,
      'courseId': courseId,
      'userId': userId,
      'isPending': isPending,
      'dateCreated': dateCreated.toIso8601String(),
    };
  }

  static BookDataModel fromJson(Map<String, dynamic> json) {
    return BookDataModel(
      id: json['id'],
      bookId: json['bookId'],
      chapterId: json['chapterId'],
      courseId: json['courseId'],
      userId: json['userId'],
      isPending: json['isPending'],
    )..dateCreated = DateTime.parse(json['dateCreated']);
  }
}
